### ISSUE TITLE
Fulfill the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/FadeButton#6]
**General**
- [x] It has a Github repo
- [x] It has a proper [.gitignore](https://github.com/inaka/swift_guidelines/wiki/.gitignore) file
- [x] It has an [Apache2 LICENSE](https://github.com/inaka/swift_guidelines/wiki/License) file
- [x] It has a clear and useful [README](https://github.com/inaka/swift_guidelines/wiki/README-Template) file
- [x] Its files and folders are [properly organized](https://github.com/inaka/swift_guidelines/wiki/Project-Organization)
- [x] It's available in [cocoapods](https://github.com/inaka/swift_guidelines/wiki/How-To-Podify)

**Code**
- [x] Code is [documented](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/)
- [ ] Code is tested
- [x] Every source file uses the [Apache2 License Header](https://github.com/inaka/swift_guidelines/wiki/License-Header)

**CI**
- [x] It's hooked to HipChat rooms
- [x] It's hooked to [Travis CI](https://github.com/inaka/swift_guidelines/wiki/Travis-CI-Hook)
- [ ] It's hooked to [Codecov](https://github.com/inaka/swift_guidelines/wiki/Codecov-Hook)

**Exhibition**
- [ ] There is a [blog post](http://inaka.net/blog) about it
- [ ] It's shared on social networks
- [ ] It's shared on [Reddit](https://www.reddit.com/)
- [ ] It's shared on [Hacker News](https://news.ycombinator.com/)
